"""Removing unique telegram key

Revision ID: 4be5af90681a
Revises: ee1415d90c70
Create Date: 2025-05-10 21:04:04.690829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be5af90681a'
down_revision: Union[str, None] = 'ee1415d90c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_login_token_key', 't_login', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('t_login_token_key', 't_login', ['token'])
    # ### end Alembic commands ###
