"""update user table

Revision ID: ae0a749dcaff
Revises: b7402df8b47d
Create Date: 2025-03-18 15:44:57.072636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae0a749dcaff'
down_revision: Union[str, None] = 'b7402df8b47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binance_coingecko_mapping')
    op.add_column('t_login', sa.Column('language', sa.String(), nullable=True))
    op.drop_column('t_login', 'end_subscription')
    op.drop_column('t_login', 'wallets')
    op.drop_column('t_login', 'api_secret')
    op.drop_column('t_login', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_login', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('t_login', sa.Column('api_secret', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('t_login', sa.Column('wallets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('t_login', sa.Column('end_subscription', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('t_login', 'language')
    op.create_table('binance_coingecko_mapping',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('binance_symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('coingecko_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='binance_coingecko_mapping_pkey')
    )
    # ### end Alembic commands ###
