"""initial tables

Revision ID: e188d1e41b2a
Revises: 0fe30e40846f
Create Date: 2025-07-09 11:58:15.382755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e188d1e41b2a'
down_revision: Union[str, None] = '0fe30e40846f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_bot_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.BigInteger(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('want_signal', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_table('t_volume_records',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.String(length=66), nullable=False),
    sa.Column('perp_volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('perp_taker_volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('perp_maker_volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('broker_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('address', sa.String(length=42), nullable=True),
    sa.Column('broker_id', sa.String(length=50), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('distributed', sa.Boolean(), nullable=True),
    sa.Column('distributed_fees_half', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('date', 'account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_volume_records')
    op.drop_table('t_login')
    op.drop_table('t_bot_status')
    # ### end Alembic commands ###
