"""Make wallet_address unique

Revision ID: ee1415d90c70
Revises: 55857f3ec9cf
Create Date: 2025-04-18 20:00:43.600460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1415d90c70'
down_revision: Union[str, None] = '55857f3ec9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 't_login', ['wallet_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_login', type_='unique')
    # ### end Alembic commands ###
