"""initial tables

Revision ID: f57afb126c2f
Revises: 
Create Date: 2025-02-08 21:48:54.632081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57afb126c2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binance_coingecko_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('binance_symbol', sa.String(), nullable=False),
    sa.Column('coingecko_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_bot_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.BigInteger(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_secret', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('want_signal', sa.Boolean(), nullable=True),
    sa.Column('wallets', sa.JSON(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('end_subscription', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('t_signal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.BigInteger(), nullable=False),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('gain_threshold', sa.Float(), nullable=False),
    sa.Column('stop_loss_threshold', sa.Float(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx2_token_pair_timeframe', 't_signal', ['token', 'pair', 'timeframe'], unique=False)
    op.create_index('idx_signal', 't_signal', ['signal'], unique=False)
    op.create_table('training_in_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_in_progress')
    op.drop_index('idx_signal', table_name='t_signal')
    op.drop_index('idx2_token_pair_timeframe', table_name='t_signal')
    op.drop_table('t_signal')
    op.drop_table('t_login')
    op.drop_table('t_bot_status')
    op.drop_table('binance_coingecko_mapping')
    # ### end Alembic commands ###
